disabled_rules:
  - weak_delegate
  - cyclomatic_complexity
  - force_unwrapping
  - function_body_length
  - type_name
  - line_length
  - identifier_name
  - trailing_whitespace

excluded:
  - .build
  - .swiftpm
  - DerivedData
  - Sources/Examples

file_length:
  warning: 500
  error: 1200

nesting:
  type_level:
    warning: 3
    error: 6
